language: rust
rust:
  - nightly
  - beta
  - stable
cache: cargo

matrix:
  allow_failures:
  - rust: nightly

before_script:
  - |
      if test "$TRAVIS_RUST_VERSION" = "nightly"; then
        test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update
        test -x $HOME/.cargo/bin/cargo-clippy || cargo install clippy
        cargo install-update clippy
      fi

script:
- cargo test
- if test "$TRAVIS_RUST_VERSION" = "nightly"; then cargo clippy; fi
